#!/usr/bin/env python3
"""Generate KEY_*/BTN_* name tables from linux/input-event-codes.h.

Outputs:
  daemon/event-names.h     - C table for config parsing in the daemon
  gui/Evdev/EventCodes.g.cs - C# dictionaries for the GUI

The first name defined for a code is treated as canonical (so 0x130 is
BTN_SOUTH, with BTN_A as an accepted alias when parsing).
"""
import re
import sys
from pathlib import Path

HEADER = Path("/usr/include/linux/input-event-codes.h")
ROOT = Path(__file__).resolve().parent.parent

DEFINE_RE = re.compile(r"^#define\s+((?:KEY|BTN)_\w+)\s+(\S+)")
SKIP_SUFFIXES = ("_MAX", "_CNT")
# Range markers that alias real buttons; we want BTN_SOUTH, not BTN_GAMEPAD.
SKIP_NAMES = {
    "BTN_MISC", "BTN_MOUSE", "BTN_JOYSTICK", "BTN_GAMEPAD", "BTN_DIGI",
    "BTN_WHEEL", "BTN_TRIGGER_HAPPY", "KEY_MIN_INTERESTING",
}

def parse():
    by_name = {}          # name -> code
    canonical = {}        # code -> first name seen
    ordered = []          # (name, code) in header order
    for line in HEADER.read_text().splitlines():
        m = DEFINE_RE.match(line)
        if not m:
            continue
        name, value = m.groups()
        if name.endswith(SKIP_SUFFIXES) or name in SKIP_NAMES:
            continue
        if value in by_name:          # alias of an earlier define
            code = by_name[value]
        else:
            try:
                code = int(value, 0)
            except ValueError:
                continue
        by_name[name] = code
        if code not in canonical:
            canonical[code] = name
        ordered.append((name, code))
    return ordered, canonical

def write_c(ordered, canonical):
    out = [
        "/* Generated by scripts/gen-event-codes.py - do not edit. */",
        "#ifndef EVENT_NAMES_H",
        "#define EVENT_NAMES_H",
        "",
        "struct ev_code_name { const char *name; int code; };",
        "",
        "static const struct ev_code_name EV_CODE_NAMES[] = {",
    ]
    for name, code in ordered:
        out.append(f'    {{ "{name}", {code:#x} }},')
    out.append("};")
    out.append(f"#define EV_CODE_NAMES_LEN {len(ordered)}")
    out.append("")
    out.append("static const struct ev_code_name EV_CANONICAL_NAMES[] = {")
    for code in sorted(canonical):
        out.append(f'    {{ "{canonical[code]}", {code:#x} }},')
    out.append("};")
    out.append(f"#define EV_CANONICAL_NAMES_LEN {len(canonical)}")
    out.append("")
    out.append("#endif")
    (ROOT / "daemon/event-names.h").write_text("\n".join(out) + "\n")

def write_cs(ordered, canonical):
    out = [
        "// Generated by scripts/gen-event-codes.py - do not edit.",
        "namespace PadBridge.Gui.Evdev;",
        "",
        "public static partial class EventCodes",
        "{",
        "    public static readonly System.Collections.Generic.Dictionary<string, int> NameToCode = new()",
        "    {",
    ]
    for name, code in ordered:
        out.append(f'        ["{name}"] = {code:#x},')
    out += [
        "    };",
        "",
        "    public static readonly System.Collections.Generic.Dictionary<int, string> CodeToName = new()",
        "    {",
    ]
    for code in sorted(canonical):
        out.append(f'        [{code:#x}] = "{canonical[code]}",')
    out += [
        "    };",
        "}",
    ]
    (ROOT / "gui/Evdev").mkdir(parents=True, exist_ok=True)
    (ROOT / "gui/Evdev/EventCodes.g.cs").write_text("\n".join(out) + "\n")

if __name__ == "__main__":
    ordered, canonical = parse()
    write_c(ordered, canonical)
    write_cs(ordered, canonical)
    print(f"wrote {len(ordered)} names, {len(canonical)} canonical codes", file=sys.stderr)
